[pytest]
pythonpath = .

addopts= -v --alluredir=allure-results

markers=
    smoke: smoke API scenarios
    workflow: workflow API scenarios
    negative: negative API scenarios
    regression: regression API scenarios
    slow: медленные тесты
    api: API-тесты
    db: db тесты

log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
